ctsms_base_uri: 'https://127.0.0.1'

sqlite_db_file: 'inquiry_exporter'
csv_dir: 'inquiry_exporter'

inquiry_data_truncate_table: 1
inquiry_data_ignore_duplicates: 0
#ecrf_data_trial_id: <your demo trial id>
#ecrf_data_api_listentries_page_size: 10
#ecrf_data_api_ecrfs_page_size: 10
#ecrf_data_api_values_page_size: 10
inquiry_data_row_block: 50
#ecrf_data_api_tagvalues_page_size: 10
#ecrf_data_api_ecrffields_page_size: 10

#ecrf_data_listentrytags:

inquiry_data_export_upload_folder: '/11. ProbandenInnen/11.6. Rekrutierung/'
inquiry_data_export_sqlite_filename: 'inquiry_%s%s'
inquiry_data_export_horizontal_csv_filename: 'inquiry_horizontal_%s%s'
inquiry_data_export_xls_filename: 'inquiry_%s%s'
inquiry_data_export_xlsx: 1
#dbtool: 'D:\workspaces\ctsms\core\db\dbtool.bat'
#dbtool: '/ctsms/dbtool.sh'
lockfile: '/ctsms/process.trial%s.inquiryexport.lock'
#ecrf_data_export_pdf_filename: 'ecrfs_%s%s'
inquiry_data_export_pdfs_filename: 'inquiry_%s_%s%s'

ignore_external_ids: 0
col_per_selection_set_value: 1
selection_set_value_separator: ', '

category_abbreviate_opts:
  word_count_limit: 0

inputfieldname_abbreviate_opts:
  word_count_limit: 1  
  word_blacklist:
    demo: 1

selectionvalue_abbreviate_opts:
  word_count_limit: 1
#  word_abbreviation_length: 5
#  word_limit: 7
  
