ctsms_base_uri: 'https://127.0.0.1'

sqlite_db_file: 'ecrf_importer'
csv_dir: 'ecrf_importer'

#clear_sections: 0
#clear_all_sections: 0
#append_selection_set_values: 0
#update_listentrytag_values: 0

#ecrf_import_filename
#import_ecrf_data_horizontal_multithreading
#import_ecrf_data_horizontal_numofthreads
#import_ecrf_data_horizontal_blocksize

#ecrf_data_trial_id: <your demo trial id>
#ecrf_data_api_listentries_page_size: 10
#ecrf_data_api_ecrfs_page_size: 10
#ecrf_data_api_values_page_size: 10
#ecrf_values_col_block: 1
#listentrytag_values_col_block: 0
#ecrf_data_api_probandlistentrytagvalues_page_size: 10
#ecrf_data_api_probandlistentrytags_page_size: 10
#ecrf_data_api_ecrffields_page_size: 10

#ecrf_proband_alias_column_name
#ecrf_proband_category_column_name
ecrf_proband_department_column_name: department
#ecrf_proband_gender_column_name
ecrf_probandlistentry_group_column_name: subject_group
ecrf_probandlistentry_status_column_name: enrollment_status
  
#dbtool: 'D:\workspaces\ctsms\core\db\dbtool.bat'
dbtool: '/ctsms/dbtool.sh'
lockfile: '/ctsms/process.trial%s.ecrfimport.lock'

ignore_external_ids: 0
col_per_selection_set_value: 1
selection_set_value_separator: ', '

#timezone: Europe/Vienna

ecrfrevision_abbreviate_opts:
  word_count_limit: 0

ecrfname_abbreviate_opts:
  word_count_limit: 0

visit_abbreviate_opts:
  word_count_limit: 0
  
section_abbreviate_opts:
  word_count_limit: 0

inputfieldname_abbreviate_opts:
  word_count_limit: 1  
  word_blacklist:
    demo: 1

selectionvalue_abbreviate_opts:
  word_count_limit: 1
#  word_abbreviation_length: 5
#  word_limit: 7
  
