ctsms_base_uri: 'https://127.0.0.1'

sqlite_db_file: 'ecrf_exporter'
csv_dir: 'ecrf_exporter'

ecrf_data_truncate_table: 1
ecrf_data_ignore_duplicates: 0
#ecrf_data_trial_id: <your demo trial id>
#ecrf_data_api_listentries_page_size: 10
#ecrf_data_api_ecrfs_page_size: 10
#ecrf_data_api_values_page_size: 10
ecrf_data_row_block: 50
#ecrf_data_api_probandlistentrytagvalues_page_size: 10
#ecrf_data_api_probandlistentrytags_page_size: 10
#ecrf_data_api_ecrffields_page_size: 10

#ecrf_proband_alias_column_name
#ecrf_proband_category_column_name
ecrf_proband_department_column_name: department
#ecrf_proband_gender_column_name
ecrf_probandlistentry_group_column_name: subject_group
ecrf_probandlistentry_status_column_name: enrollment_status

ecrf_data_export_upload_folder: '/4. CRF/eCRF Exports/'
ecrf_data_export_sqlite_filename: 'ecrf_%s%s'
ecrf_data_export_horizontal_csv_filename: 'ecrf_horizontal_%s%s'
ecrf_data_export_xls_filename: 'ecrf_%s%s'
ecrf_data_export_xlsx: 1
#dbtool: 'D:\workspaces\ctsms\core\db\dbtool.bat'
dbtool: '/ctsms/dbtool.sh'
lockfile: '/ctsms/process.trial%s.ecrfexport.lock'
ecrf_data_export_pdf_filename: 'ecrf_ecrfs_%s%s'
ecrf_data_export_pdfs_filename: 'ecrf_ecrf_%s_%s%s'

audit_trail_export_xls_filename: 'ecrf_issues_%s%s'
ecrf_journal_export_xls_filename: 'ecrf_changelog_%s%s'
ecrfs_export_xls_filename: 'ecrf_setup_%s%s'

proband_list_filename: '%s_%s%s'

ignore_external_ids: 0
col_per_selection_set_value: 1
selection_set_value_separator: ', '

#timezone: Europe/Vienna

ecrfrevision_abbreviate_opts:
  word_count_limit: 0

ecrfname_abbreviate_opts:
  word_count_limit: 0

visit_abbreviate_opts:
  word_count_limit: 0
  
section_abbreviate_opts:
  word_count_limit: 0

inputfieldname_abbreviate_opts:
  word_count_limit: 1  
  word_blacklist:
    demo: 1

selectionvalue_abbreviate_opts:
  word_count_limit: 1
#  word_abbreviation_length: 5
#  word_limit: 7
  
